using System.ComponentModel.DataAnnotations;

namespace template.Models.InputModels
{
    public class CategoryInputModel
    {
        [Required]
        [MaxLength(60)]
        public string Name { get; set; }

        //default value = 0
        public int ParentCategoryId { get; set; }

        //should be generated by -, eg science-fiction
        public string Slug { get; set; }
    }
}